apiVersion: v1
kind: Service
metadata:
  name: myapp-dbsvc
  labels:
    app: phonebook
spec:
  type: ClusterIP
  selector:
    app: phonebook
  ports:
  - name: myapp
    protocol: TCP
    port: 3306
    targetPort: 3306