apiVersion: v1
kind: PersistentVolume
metadata:
   name: myapp-pv
   labels:
     app: phonebook
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: findme
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"