apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  labels:
    app: phonebook
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: findme