apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-resultdeployment
  labels:
    app: phonebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
        - name: web-container
          image: hivelkrasniqi/search
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: my-config
          - secretRef:
              name: mysql-secret
