apiVersion: v1
kind: Service
metadata:
  name: myapp-resultsvc
  labels:
    app: phonebook
spec:
  type: NodePort
  selector:
    app: phonebook
  ports:
   - name: myapp
     port: 80
     targetPort: 80
     nodePort: 30002
