apiVersion: v1
kind: Service
metadata:
  name: myapp-websvc
  labels:
    app: phonebook
spec:
  type: NodePort
  selector:
    app: phonebook
  ports:
  - name: myapp
    port: 80
    targetPort: 80
    nodePort: 30001
